export const SET_ALBUMS = 'SET_ALBUMS';
export const ADD_ALBUMS = 'ADD_ALBUMS';
export const SET_ARTISTS = 'SET_ARTISTS';
export const ADD_ARTISTS = 'ADD_ARTISTS';
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const SET_SONG = 'SET_SONG';
export const ADD_SONG = 'ADD_SONG';
//can be obtained in Spotify client using "copy link" or "embed playlist"
//some are called "Viral 50". They're also made by Spotify, though
export const COUNTRY_ID = {
    "andorra": "37i9dQZEVXbMxjQJh4Um8T",
    "argentina": "37i9dQZEVXbMMy2roB9myp",
    "australia": "37i9dQZEVXbJPcfkRz0wJ0",
    "austria": "37i9dQZEVXbKNHh6NIXu36",
    "belgium": "37i9dQZEVXbJNSeeHswcKB",
    "bolivia": "37i9dQZEVXbJqfMFK4d691",
    "brazil": "37i9dQZEVXbMXbN3EUUhlg",
    "bulgaria": "37i9dQZEVXbNfM2w2mq1B8",
    "canada": "37i9dQZEVXbKj23U1GF4IR",
    "chile": "37i9dQZEVXbL0GavIqMTeb",
    "colombia": "37i9dQZEVXbOa2lmxNORXQ",
    "costa_rica": "37i9dQZEVXbMZAjGMynsQX",
    "cyprus": "37i9dQZEVXbNBxnXSWuAcX",
    "czech_republic": "37i9dQZEVXbIP3c3fqVrJY",
    "denmark": "37i9dQZEVXbL3J0k32lWnN",
    "dominican_republic": "37i9dQZEVXbKAbrMR8uuf7",
    "ecuador": "37i9dQZEVXbJlM6nvL1nD1",
    "egypt": "37i9dQZEVXbLn7RQmT5Xv2",
    "el_salvador": "37i9dQZEVXbLxoIml4MYkT",
    "estonia": "37i9dQZEVXbLesry2Qw2xS",
    "finland": "37i9dQZEVXbMxcczTSoGwZ",
    "france": "37i9dQZEVXbIPWwFssbupI",
    "germany": "37i9dQZEVXbJiZcmkrIHGU",
    "greece": "37i9dQZEVXbJqdarpmTJDL",
    "guatemala": "37i9dQZEVXbLy5tBFyQvd4",
    "hong_kong": "37i9dQZEVXbLwpL8TjsxOG",
    "honduras": "37i9dQZEVXbJp9wcIM9Eo5",
    "hungary": "37i9dQZEVXbNHwMxAkvmF8",
    "india": "37i9dQZEVXbLZ52XmnySJg",
    "indonesia": "37i9dQZEVXbObFQZ3JLcXt",
    "ireland": "37i9dQZEVXbKM896FDX8L1",
    "israel": "37i9dQZEVXbJ6IpvItkve3",
    "iceland": "37i9dQZEVXbKMzVsSGQ49S",
    "italy": "37i9dQZEVXbIQnj7RRhdSX",
    "japan": "37i9dQZEVXbKXQ4mDTEBXq",
    "south_korea": "37i9dQZEVXbNxXF4SkHj9F",
    "lithuania": "37i9dQZEVXbMx56Rdq5lwc",
    "latvia": "37i9dQZEVXbJWuzDrTxbKS",
    "morocco": "37i9dQZEVXbJU9eQpX8gPT",
    "mexico": "37i9dQZEVXbO3qyFxbkOE1",
    "malaysia": "37i9dQZEVXbJlfUljuZExa",
    "nicaragua": "37i9dQZEVXbISk8kxnzfCq",
    "netherlands": "37i9dQZEVXbKCF6dqVpDkS",
    "norway": "37i9dQZEVXbJvfa0Yxg7E7",
    "new_zealand": "37i9dQZEVXbM8SIrkERIYl",
    "panama": "37i9dQZEVXbKypXHVwk1f0",
    "peru": "37i9dQZEVXbJfdy5b0KP7W",
    "philippines": "37i9dQZEVXbNBz9cRCSFkY",
    "poland": "37i9dQZEVXbN6itCcaL3Tt",
    "portugal": "37i9dQZEVXbKyJS56d1pgi",
    "paraguay": "37i9dQZEVXbNOUPGj7tW6T",
    "romania": "37i9dQZEVXbNZbJ6TZelCq",
    "russia": "37i9dQZEVXbL8l7ra5vVdB",
    "saudi_arabia": "37i9dQZEVXbLrQBcXqUtaC",
    "singapore": "37i9dQZEVXbK4gjvS1FjPY",
    "slovakia": "37i9dQZEVXbKIVTPX9a2Sb",
    "spain": "37i9dQZEVXbNFJfN1Vw8d9",
    "south_africa": "37i9dQZEVXbMH2jvi6jvjk",
    "sweden": "37i9dQZEVXbLoATJ81JYXz",
    "switzerland": "37i9dQZEVXbJiyhoAPEfMK",
    "thailand": "37i9dQZEVXbMnz8KIWsvf9",
    "turkey": "37i9dQZEVXbIVYVBNw9D5K",
    "taiwan": "37i9dQZEVXbMnZEatlMSiu",
    "ukraine": "37i9dQZEVXbKkidEfWYRuD",
    "uruguay": "37i9dQZEVXbMJJi3wgRbAy",
    "vietnam": "37i9dQZEVXbLdGSmz6xilI"
};